### ISSUE TITLE
APPLICATION_STORE never defined when checked

### ISSUE THREAD

**Issue by Zwaen91** [spryker-sdk/integrator#39]
Triggered by post-update-cmd the SprykerSdk\Integrator\Plugin\Composer\InstallerComposerPlugin calls at some point
SprykerSdk\Integrator\IntegratorConfig->prepareSharedConfigDependencies() which checks if 'APPLICATION_STORE' is defined. At this point it is not and 'DE' will be set. First problem is that the Env is not defined at this point at second point is that DE is not existing when renaming the stores.

**Comment by dereuromark** [comment]
Tracked as https://spryker.atlassian.net/browse/PPLUS-1768

**Comment by Kyrylo-Meretskyi** [comment]
@Zwaen91 Could you please show the way you trigger the `SprykerSdk\Integrator\Plugin\Composer\InstallerComposerPlugin`?

**Comment by vol4onok** [comment]
Could you give some information about the project? where did you run it?  The result of this command can depend on the project.

**Comment by Zwaen91** [comment]
Don't need it anymore.
